language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
branches:
  only:
  - master
install:
  - npm install
  - git clone https://${GH_TOKEN}@github.com/aui/uglifyjs-webpack-plugin.git lib/uglifyjs-webpack-plugin
  - cd lib/uglifyjs-webpack-plugin
  - npm install
script:
  - npm run build
  - npm run build:parallel
  - npm run build:parallel:cache